name: Build Aseprite Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: aseprite/get-ninja@main

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Install Skia
        shell: bash
        run: |
          this_dir=$(cygpath "${{ github.workspace }}")
          skia_url=$(source $this_dir/laf/misc/skia-url.sh | xargs)
          skia_file=$(basename $skia_url)
          curl --ssl-revoke-best-effort -L -o "$skia_file" "$skia_url"
          unzip "$skia_file" -d skia

      - name: Configure with CMake (Release)
        shell: bash
        run: |
          export laf_backend=skia
          export enable_scripting=on
          export enable_ccache=off
          export skia_arch=x64
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DLAF_BACKEND=$laf_backend \
            -DENABLE_SCRIPTING=$enable_scripting \
            -DENABLE_CCACHE=$enable_ccache \
            -DSKIA_DIR=$(realpath skia) \
            -DSKIA_LIBRARY_DIR=$(realpath skia/out/Release-$skia_arch)

      - name: Compile Aseprite
        shell: bash
        run: cd build && ninja

      - name: Package Clean Release
        run: |
          mkdir release
          copy build\bin\aseprite.exe release\

      - name: Upload Aseprite Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-release
          path: release/
